# https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  default: none
  enable:
    - govet
    - misspell
    - errcheck
  settings:
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    errcheck:
      check-type-assertions: false
      check-blank: false
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

issues:
  max-same-issues: 0
