name: check golangci-lint config
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golangci-lint-version: ["v1", "v2"]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set TAG_NAME
        if: ${{ matrix.golangci-lint-version == 'v1' }}
        run: echo "TAG_NAME=v1.64.8" >> "$GITHUB_ENV"
      - name: Set TAG_NAME
        if: ${{ matrix.golangci-lint-version != 'v1' }}
        run: echo "TAG_NAME=$(gh release list --repo golangci/golangci-lint --json name,isLatest --jq '.[] | select(.isLatest) | .name')" >> "$GITHUB_ENV"
      - name: Install golangci-lint
        run: |
          curl -sSfL "https://raw.githubusercontent.com/golangci/golangci-lint/refs/tags/$TAG_NAME/install.sh" | sh -s -- -b "$(go env GOPATH)/bin" "$TAG_NAME"
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Validate golangci-lint config
        run: golangci-lint config verify --config=.github/.golangci.${{ matrix.golangci-lint-version }}.yml
