name: check golangci-lint config
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golangci-lint-version: ["v1", "v2"]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 #v6.5.2
        with:
          version: ${{ matrix.golangci-lint-version == 'v1' && 'v1.64.8' || 'latest' }}
      - name: Validate golangci-lint config
        run: golangci-lint config verify --config=.github/.golangci.${{ matrix.golangci-lint-version }}.yml
